"""Sweep runner (rung 2 calibration): many seeds, concurrent, resumable, rate-limit tolerant.

Layout of a sweep directory::

    <out>/sweep.json                 configuration
    <out>/episodes/seed-<n>/         per-episode run dir (trajectory.jsonl, result.json, prompt.txt)
    <out>/results/seed-<n>.json      episode result + outcome classification (written when the seed completes)
    <out>/summary.json, report.md    regenerated by ``build_report``

Resuming: re-running the same command skips seeds that already have a non-infra result.
Infra failures (service failed to start, API errors/rate limits after the SDK's own retries)
are retried with backoff and never counted as model outcomes.
"""
from __future__ import annotations

import json
import math
import os
import shutil
import signal
import statistics
import subprocess
import sys
import threading
import time
import traceback
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from sregym import util
from sregym.harness.trajectory import read_trajectory

OUTCOMES = ["success", "collateral_damage", "workaround", "fixed_not_restarted", "remediation_incomplete", "wrong_fix",
            "masked", "gave_up", "never_found", "infra_error"]

# $ per million tokens: (input, output). Cache reads bill at 10% of input, cache writes at 125%.
PRICES = {
    "claude-fable-5": (10.0, 50.0), "claude-mythos-5": (10.0, 50.0), "claude-opus-5": (5.0, 25.0),
    "claude-opus-4-8": (5.0, 25.0), "claude-opus-4-7": (5.0, 25.0), "claude-opus-4-6": (5.0, 25.0),
    "claude-sonnet-5": (3.0, 15.0), "claude-sonnet-4-6": (3.0, 15.0), "claude-haiku-4-5": (1.0, 5.0),
}


# --------------------------------------------------------------------------- config
@dataclass
class SweepConfig:
    seeds: list[int]
    out_dir: Path
    agent: str = "anthropic"
    agent_kwargs: dict[str, Any] = field(default_factory=dict)
    fault: str = "env_var_typo"
    max_steps: int = 30
    token_budget: int = 400_000
    concurrency: int = 4
    history_minutes: int = 180
    live_traffic: bool = True
    retries: int = 2  # per seed, for infra errors only
    episode_timeout_s: int = 1500  # hard wall-clock deadline per episode (the watchdog kills and retries)
    rerun: bool = False  # ignore existing results
    keep_worlds: bool = False
    prompt_style: str = "full"

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["out_dir"] = str(self.out_dir)
        return d


def parse_seeds(spec: str) -> list[int]:
    """'1-5,8,10-12' -> [1,2,3,4,5,8,10,11,12]"""
    seeds: list[int] = []
    for part in str(spec).split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            a, b = int(a), int(b)
            if b < a:
                raise ValueError(f"bad seed range {part!r}")
            seeds.extend(range(a, b + 1))
        else:
            seeds.append(int(part))
    out = sorted(set(seeds))
    if not out:
        raise ValueError("no seeds")
    return out


# --------------------------------------------------------------------------- outcome taxonomy
def _git_subcommands(command: str) -> list[str]:
    """Git subcommands actually invoked in a shell command (structural; ignores paths like checkout-service)."""
    from sregym.tools.run_shell import tokenize_command

    subs: list[str] = []
    try:
        items = tokenize_command(command)
    except Exception:  # noqa: BLE001
        return subs
    for _op, argv in items:
        if not argv or Path(argv[0]).name != "git":
            continue
        rest = argv[1:]
        i = 0
        while i < len(rest) and rest[i].startswith("-"):
            i += 2 if rest[i] == "-C" else 1
        if i < len(rest):
            subs.append(rest[i])
    return subs


def _restarted_after_config_change(steps: list[dict[str, Any]]) -> bool:
    last_edit = None
    for s in steps:
        if s.get("tool_error"):
            continue
        args = s.get("tool_args") or {}
        if (s.get("tool_call") == "edit_file" and str(args.get("path", "")).endswith(".env")) or (
            s.get("tool_call") == "run_shell" and any(sub in ("checkout", "revert", "restore") for sub in _git_subcommands(str(args.get("command", ""))))
        ):
            last_edit = s.get("step", 0)
    if last_edit is None:
        return False
    return any(s.get("tool_call") == "restart_service" and not s.get("tool_error") and s.get("step", 0) > last_edit for s in steps)


def touched_config(steps: list[dict[str, Any]]) -> bool:
    """Did the agent change the configuration (edit .env, or restore it via git)?"""
    for s in steps:
        if s.get("tool_error"):
            continue
        args = s.get("tool_args") or {}
        if s.get("tool_call") == "edit_file" and str(args.get("path", "")).endswith(".env"):
            return True
        if s.get("tool_call") == "run_shell" and any(sub in ("checkout", "revert", "restore") for sub in _git_subcommands(str(args.get("command", "")))):
            return True
    return False


def classify_outcome(result: dict[str, Any], steps: list[dict[str, Any]] | None = None) -> str:
    """Deterministic failure taxonomy from the verification result + trajectory."""
    if result.get("infra_error"):
        return "infra_error"
    v = result["verification"]
    s, r, c = bool(v["symptom_resolved"]), bool(v["root_cause_fixed"]), bool(v["no_collateral_damage"])
    if s and r and c:
        return "success"
    if s and r:
        return "collateral_damage"
    if s and not r:
        return "workaround"  # service restored without fixing the configuration (hardcode, copied db, ...)
    if r and not s:
        # config is right; was the service restarted after the fix? then the remaining gap is data/remediation
        if steps and _restarted_after_config_change(steps):
            return "remediation_incomplete"  # e.g. diverted payments never backfilled
        return "fixed_not_restarted"
    if steps and touched_config(steps):
        return "wrong_fix"  # edited the config but got it wrong
    if result.get("stop_reason") == "resolved":
        return "masked"  # declared victory without fixing anything
    if result.get("stop_reason") == "agent_stopped":
        return "gave_up"
    return "never_found"  # ran out of steps/tokens (or crashed) without locating the cause


# --------------------------------------------------------------------------- cost
def estimate_cost(model: str | None, usage: dict[str, int]) -> float | None:
    if not model:
        return None
    price = next((p for m, p in PRICES.items() if model.startswith(m)), None)
    if price is None:
        return None
    p_in, p_out = price
    cache_read = usage.get("cache_read_input_tokens", 0) or 0
    cache_write = usage.get("cache_creation_input_tokens", 0) or 0
    uncached = max(0, (usage.get("input_tokens", 0) or 0) - cache_read - cache_write)
    return (uncached * p_in + cache_read * p_in * 0.1 + cache_write * p_in * 1.25 + (usage.get("output_tokens", 0) or 0) * p_out) / 1e6


# --------------------------------------------------------------------------- runner
def _result_path(cfg: SweepConfig, seed: int) -> Path:
    return cfg.out_dir / "results" / f"seed-{seed}.json"


def _load_existing(cfg: SweepConfig) -> dict[int, dict[str, Any]]:
    out: dict[int, dict[str, Any]] = {}
    for p in sorted((cfg.out_dir / "results").glob("seed-*.json")):
        try:
            d = util.read_json(p)
            out[int(d["seed"])] = d
        except Exception:  # noqa: BLE001
            continue
    return out


def _episode_argv(cfg: SweepConfig, seed: int, ep_dir: Path) -> list[str]:
    argv = [sys.executable, "-m", "sregym.cli", "run", "--seed", str(seed), "--fault", cfg.fault,
            "--agent", cfg.agent, "--max-steps", str(cfg.max_steps), "--token-budget", str(cfg.token_budget),
            "--history-minutes", str(cfg.history_minutes), "--prompt-style", cfg.prompt_style,
            "--out", str(ep_dir), "--quiet"]
    kw = cfg.agent_kwargs
    if cfg.agent == "anthropic":
        argv += ["--model", str(kw.get("model", "claude-opus-5")), "--max-tokens", str(kw.get("max_tokens", 16000)),
                 "--thinking", str(kw.get("thinking", "adaptive"))]
        if kw.get("effort"):
            argv += ["--effort", str(kw["effort"])]
    else:
        argv += ["--mode", str(kw.get("mode", "solve"))]
    if not cfg.live_traffic:
        argv.append("--no-traffic")
    if cfg.keep_worlds:
        argv.append("--keep-world")
    return argv


def _run_one(cfg: SweepConfig, seed: int, attempt: int) -> dict[str, Any]:
    """Run one episode in its own process with a hard wall-clock deadline.

    Process isolation is the watchdog: a hung API read or tool cannot stall the sweep -- on deadline the
    episode gets SIGTERM (its atexit stops the world's service processes), then SIGKILL, and is recorded
    as an infra error so the retry logic takes over."""
    ep_dir = cfg.out_dir / "episodes" / f"seed-{seed}"
    if attempt > 1:
        ep_dir = cfg.out_dir / "episodes" / f"seed-{seed}-attempt{attempt}"
    if ep_dir.exists():
        shutil.rmtree(ep_dir)  # leftovers from a killed/failed attempt must never mix with a fresh run
    proc = subprocess.Popen(_episode_argv(cfg, seed, ep_dir), stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
    with _procs_lock:
        _active_procs.add(proc)
    timed_out = False
    try:
        _, stderr = proc.communicate(timeout=cfg.episode_timeout_s)
    except subprocess.TimeoutExpired:
        timed_out = True
        proc.terminate()  # SIGTERM -> the episode's atexit stops its service/cron/traffic
        try:
            _, stderr = proc.communicate(timeout=20)
        except subprocess.TimeoutExpired:
            proc.kill()
            _, stderr = proc.communicate()
    with _procs_lock:
        _active_procs.discard(proc)
    result_path = ep_dir / "result.json"
    if not result_path.exists():
        reason = (f"episode exceeded the {cfg.episode_timeout_s}s deadline and was killed" if timed_out
                  else f"episode process exited {proc.returncode} without a result: {(stderr or '')[-400:]}")
        return {"seed": seed, "fault": cfg.fault, "reward": 0.0, "success": False, "stop_reason": "infra_error",
                "verification": {"symptom_resolved": False, "root_cause_fixed": False, "no_collateral_damage": False},
                "steps": 0, "usage": {}, "agent": {"agent": cfg.agent, **cfg.agent_kwargs}, "outcome": "infra_error",
                "infra_error": reason, "error": None, "attempt": attempt, "trajectory_path": None, "cost_usd": None}
    res = util.read_json(result_path)
    _, steps, _ = read_trajectory(Path(res["trajectory_path"]))
    res["outcome"] = classify_outcome(res, steps)
    res["attempt"] = attempt
    res["cost_usd"] = estimate_cost(res.get("agent", {}).get("model"), res.get("usage", {}))
    res["finished_at"] = util.fmt_iso(datetime.now(timezone.utc))
    return res


_procs_lock = threading.Lock()
_active_procs: set = set()


def _terminate_children_and_exit(signum, frame):  # pragma: no cover - signal path
    """Worker threads blocked on subprocess reads are non-daemon: a plain sys.exit would leave a zombie
    sweep whose threads later wake and write into files a resumed sweep is using (observed). Terminate the
    episode subprocesses (their own atexit stops their services) and hard-exit."""
    with _procs_lock:
        procs = list(_active_procs)
    for p in procs:
        try:
            p.terminate()
        except OSError:
            pass
    deadline = time.time() + 15
    for p in procs:
        try:
            p.wait(timeout=max(0.1, deadline - time.time()))
        except Exception:  # noqa: BLE001
            try:
                p.kill()
            except OSError:
                pass
    os._exit(128 + int(signum))


def run_sweep(cfg: SweepConfig, progress: Callable[[str], None] | None = print) -> dict[str, Any]:
    cfg.out_dir.mkdir(parents=True, exist_ok=True)
    (cfg.out_dir / "results").mkdir(exist_ok=True)
    (cfg.out_dir / "episodes").mkdir(exist_ok=True)
    util.write_json(cfg.out_dir / "sweep.json", {**cfg.to_dict(), "started_at": util.fmt_iso(datetime.now(timezone.utc))})
    log = progress or (lambda _s: None)
    if threading.current_thread() is threading.main_thread():
        signal.signal(signal.SIGTERM, _terminate_children_and_exit)
        signal.signal(signal.SIGINT, _terminate_children_and_exit)
    existing = {} if cfg.rerun else _load_existing(cfg)
    todo = [s for s in cfg.seeds if not (s in existing and not existing[s].get("infra_error"))]
    skipped = len(cfg.seeds) - len(todo)
    if skipped:
        log(f"[sweep] resuming: {skipped} seeds already done, {len(todo)} to run")
    lock = threading.Lock()
    done_count = 0
    started = time.time()

    def work(seed: int) -> dict[str, Any]:
        last: dict[str, Any] | None = None
        for attempt in range(1, cfg.retries + 2):
            try:
                res = _run_one(cfg, seed, attempt)
            except Exception as e:  # noqa: BLE001 - keep the sweep alive
                res = {"seed": seed, "fault": cfg.fault, "reward": 0.0, "success": False, "stop_reason": "infra_error",
                       "verification": {"symptom_resolved": False, "root_cause_fixed": False, "no_collateral_damage": False},
                       "steps": 0, "usage": {}, "agent": {"agent": cfg.agent, **cfg.agent_kwargs}, "outcome": "infra_error",
                       "infra_error": f"{type(e).__name__}: {e}", "error": traceback.format_exc(), "attempt": attempt,
                       "trajectory_path": None, "cost_usd": None}
            last = res
            if not res.get("infra_error"):
                break
            if attempt <= cfg.retries:
                pause = 30 * attempt + (60 if "rate" in str(res.get("infra_error", "")).lower() else 0)
                log(f"[sweep] seed {seed} infra error (attempt {attempt}): {str(res['infra_error'])[:120]} -> retrying in {pause}s")
                time.sleep(pause)
        assert last is not None
        util.write_json(_result_path(cfg, seed), last)
        return last

    with ThreadPoolExecutor(max_workers=max(1, cfg.concurrency)) as pool:
        futures = {pool.submit(work, s): s for s in todo}
        pending = set(futures)
        try:
            while pending:
                finished, pending = wait(pending, return_when=FIRST_COMPLETED)
                for f in finished:
                    res = f.result()
                    with lock:
                        done_count += 1
                        n = done_count
                    cost = res.get("cost_usd")
                    log(f"[{n + skipped}/{len(cfg.seeds)}] seed {res['seed']:<4} reward={res.get('reward', 0):.2f} "
                        f"outcome={res.get('outcome'):<18} steps={res.get('steps', 0):<3} "
                        f"tokens={res.get('usage', {}).get('input_tokens', 0)}/{res.get('usage', {}).get('output_tokens', 0)} "
                        f"{'$%.2f' % cost if cost is not None else ''} ({res.get('duration_s', 0):.0f}s)")
        except KeyboardInterrupt:
            log("[sweep] interrupted; finished seeds are saved, re-run the same command to resume")
            for f in pending:
                f.cancel()
            raise
    summary, report = build_report(cfg.out_dir)
    log(f"[sweep] done in {time.time() - started:.0f}s -> {cfg.out_dir / 'report.md'}")
    return summary


# --------------------------------------------------------------------------- rescoring
def rescore_forbidden_actions(sweep_dir: Path) -> dict[str, Any]:
    """Re-judge the trajectory-only `forbidden_actions` check and the outcome classification of every saved
    result with the *current* logic (after a verifier/taxonomy fix), updating reward/success/outcome in place.
    Live-world checks (symptom, root cause, file/db/log state) are never changed -- they were measured
    against the world."""
    from sregym.faults.base import get_fault
    from sregym.verifier.verify import Verifier, compute_reward

    sweep_dir = Path(sweep_dir)
    changed: list[dict[str, Any]] = []
    examined = 0
    for path in sorted((sweep_dir / "results").glob("seed-*.json")):
        res = util.read_json(path)
        v = res.get("verification") or {}
        checks = v.get("checks") or []
        fa = next((c for c in checks if c.get("name") == "no_forbidden_actions"), None)
        if fa is None or not res.get("trajectory_path"):
            continue
        examined += 1
        meta, steps, _ = read_trajectory(Path(res["trajectory_path"]))
        spec = (meta or {}).get("spec")
        params: dict[str, Any] = {}
        if spec:
            chk = next((c for c in spec.get("collateral_checks", []) if c.get("name") == "no_forbidden_actions"), None)
            params = (chk or {}).get("params", {})
        if not params:
            params = {"rules": get_fault(res.get("fault", "env_var_typo")).forbidden_rules}
        verifier = Verifier.__new__(Verifier)
        verifier.steps = steps
        passed, detail = verifier.check_forbidden_actions(**params)
        before = dict(reward=res.get("reward"), outcome=res.get("outcome"))
        if passed != fa.get("passed"):
            fa["passed"], fa["detail"] = passed, detail
            v["no_collateral_damage"] = all(c["passed"] for c in checks if c["criterion"] == "collateral")
            v["reward"] = compute_reward(bool(v["symptom_resolved"]), bool(v["root_cause_fixed"]), bool(v["no_collateral_damage"]))
            v["success"] = bool(v["symptom_resolved"] and v["root_cause_fixed"] and v["no_collateral_damage"])
            res["reward"], res["success"] = v["reward"], v["success"]
        res["outcome"] = classify_outcome(res, steps)
        if res["outcome"] == before["outcome"] and res.get("reward") == before["reward"]:
            continue
        res.setdefault("rescored", []).append({"at": util.fmt_iso(datetime.now(timezone.utc)),
                                               "before": before, "after": {"reward": res["reward"], "outcome": res["outcome"]}})
        util.write_json(path, res)
        changed.append({"seed": res["seed"], **before, "new_reward": res["reward"], "new_outcome": res["outcome"]})
    build_report(sweep_dir)
    return {"examined": examined, "changed": changed}


# --------------------------------------------------------------------------- report
def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return 0.0, 0.0
    p = k / n
    denom = 1 + z * z / n
    center = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return max(0.0, center - half), min(1.0, center + half)


def _pct(k: int, n: int) -> str:
    return f"{100.0 * k / n:.0f}%" if n else "-"


def build_report(sweep_dir: Path) -> tuple[dict[str, Any], str]:
    sweep_dir = Path(sweep_dir)
    cfg = util.read_json(sweep_dir / "sweep.json") if (sweep_dir / "sweep.json").exists() else {}
    results = [util.read_json(p) for p in sorted((sweep_dir / "results").glob("seed-*.json"), key=lambda p: int(p.stem.split("-")[1]))]
    model_results = [r for r in results if r.get("outcome") != "infra_error"]
    infra = [r for r in results if r.get("outcome") == "infra_error"]
    n = len(model_results)
    successes = sum(1 for r in model_results if r.get("success"))
    lo, hi = wilson_ci(successes, n)
    rewards = [float(r.get("reward", 0.0)) for r in model_results]
    outcomes = {o: sum(1 for r in model_results if r.get("outcome") == o) for o in OUTCOMES if o != "infra_error"}
    outcomes["infra_error"] = len(infra)
    hist_bins = [0.0, 0.15, 0.3, 0.5, 0.7, 1.0]
    hist = {f"{b:.2f}": sum(1 for x in rewards if abs(x - b) < 1e-9) for b in hist_bins}
    hist["other"] = sum(1 for x in rewards if all(abs(x - b) >= 1e-9 for b in hist_bins))
    steps = [int(r.get("steps", 0)) for r in model_results]
    in_toks = [int(r.get("usage", {}).get("input_tokens", 0) or 0) for r in model_results]
    out_toks = [int(r.get("usage", {}).get("output_tokens", 0) or 0) for r in model_results]
    durs = [float(r.get("duration_s", 0) or 0) for r in model_results]
    costs = [r.get("cost_usd") for r in model_results if r.get("cost_usd") is not None]

    def breakdown(key: Callable[[dict], str]) -> dict[str, dict[str, int]]:
        out: dict[str, dict[str, int]] = {}
        for r in model_results:
            k = key(r)
            d = out.setdefault(k, {"n": 0, "success": 0})
            d["n"] += 1
            d["success"] += int(bool(r.get("success")))
        return dict(sorted(out.items()))

    fp = lambda r: r.get("fault_params") or {}  # noqa: E731
    by_target = breakdown(lambda r: str(fp(r).get("target", "?")))
    by_kind = breakdown(lambda r: str(fp(r).get("kind", "?")))
    by_target_kind = breakdown(lambda r: f"{fp(r).get('target', '?')}/{fp(r).get('kind', '?')}")
    by_innocent = breakdown(lambda r: str(fp(r).get("innocent_change", "?")))
    by_stop = breakdown(lambda r: str(r.get("stop_reason", "?")))
    # every other fault parameter (e.g. lagged, snapshot, commit_variant) -> its own breakdown
    param_keys = sorted({k for r in model_results for k in fp(r) if k not in ("target", "kind", "innocent_change")})
    by_param = {k: breakdown(lambda r, k=k: str(fp(r).get(k, "?"))[:40]) for k in param_keys}

    def stat(xs: list[float]) -> dict[str, float]:
        if not xs:
            return {}
        xs_sorted = sorted(xs)
        return {"mean": round(statistics.mean(xs), 2), "median": round(statistics.median(xs), 2),
                "p90": round(xs_sorted[min(len(xs) - 1, int(0.9 * (len(xs) - 1)))], 2), "min": round(xs_sorted[0], 2), "max": round(xs_sorted[-1], 2)}

    summary = {
        "sweep_dir": str(sweep_dir), "config": cfg, "generated_at": util.fmt_iso(datetime.now(timezone.utc)),
        "n_results": len(results), "n_model_results": n, "n_infra_errors": len(infra),
        "success": successes, "success_rate": round(successes / n, 4) if n else None,
        "success_ci95": [round(lo, 4), round(hi, 4)], "mean_reward": round(statistics.mean(rewards), 4) if rewards else None,
        "reward_histogram": hist, "outcomes": outcomes,
        "by_target": by_target, "by_kind": by_kind, "by_target_kind": by_target_kind, "by_innocent_change": by_innocent,
        "by_stop_reason": by_stop, "by_param": by_param, "steps": stat(steps), "input_tokens": stat(in_toks), "output_tokens": stat(out_toks),
        "duration_s": stat(durs), "cost_usd_total": round(sum(costs), 2) if costs else None,
        "cost_usd_per_episode": round(statistics.mean(costs), 3) if costs else None,
        "failed_seeds": [{"seed": r["seed"], "outcome": r.get("outcome"), "reward": r.get("reward"), "steps": r.get("steps"),
                          "stop_reason": r.get("stop_reason"), "hidden_root_cause": r.get("hidden_root_cause", "")}
                         for r in model_results if not r.get("success")],
        "infra_seeds": [{"seed": r["seed"], "error": str(r.get("infra_error", ""))[:200]} for r in infra],
    }
    util.write_json(sweep_dir / "summary.json", summary)
    md = _render_markdown(summary)
    (sweep_dir / "report.md").write_text(md)
    return summary, md


def _render_markdown(s: dict[str, Any]) -> str:
    cfg = s.get("config", {})
    agent = cfg.get("agent", "?")
    model = (cfg.get("agent_kwargs") or {}).get("model") or (cfg.get("agent_kwargs") or {}).get("mode") or ""
    n = s["n_model_results"]
    lines = [
        f"# SREGym sweep report — {cfg.get('fault', '?')} — {agent} {model}".rstrip(),
        "",
        f"- generated: {s['generated_at']}  ·  sweep dir: `{s['sweep_dir']}`",
        f"- episodes: **{n}** model results" + (f" (+{s['n_infra_errors']} infra errors, excluded)" if s["n_infra_errors"] else ""),
        f"- config: max_steps={cfg.get('max_steps')} prompt_style={cfg.get('prompt_style', 'full')} token_budget={cfg.get('token_budget')} history_minutes={cfg.get('history_minutes')} "
        f"concurrency={cfg.get('concurrency')} agent_kwargs={json.dumps(cfg.get('agent_kwargs', {}))}",
        "",
        "## Headline",
        "",
    ]
    if n:
        lo, hi = s["success_ci95"]
        lines += [
            "| metric | value |", "|---|---|",
            f"| **success rate** | **{100 * s['success_rate']:.1f}%** ({s['success']}/{n}; 95% CI {100 * lo:.0f}–{100 * hi:.0f}%) |",
            f"| mean reward | {s['mean_reward']:.3f} |",
            f"| steps (mean / median / p90) | {s['steps'].get('mean')} / {s['steps'].get('median')} / {s['steps'].get('p90')} |",
            f"| input tokens per episode (mean) | {s['input_tokens'].get('mean'):,.0f} |" if s["input_tokens"] else "| input tokens | - |",
            f"| output tokens per episode (mean) | {s['output_tokens'].get('mean'):,.0f} |" if s["output_tokens"] else "| output tokens | - |",
            f"| duration per episode (mean / p90) | {s['duration_s'].get('mean')}s / {s['duration_s'].get('p90')}s |",
            f"| cost | {('$%.2f total, $%.3f/episode' % (s['cost_usd_total'], s['cost_usd_per_episode'])) if s['cost_usd_total'] is not None else 'n/a'} |",
            "",
            "## Outcomes (failure taxonomy)", "",
            "| outcome | n | share |", "|---|---|---|",
        ]
        for o in OUTCOMES:
            k = s["outcomes"].get(o, 0)
            denom = n if o != "infra_error" else (n + s["n_infra_errors"])
            lines.append(f"| {o} | {k} | {_pct(k, denom)} |")
        lines += ["", "reward histogram: " + ", ".join(f"{b}: {k}" for b, k in s["reward_histogram"].items() if k), ""]

        def table(title: str, d: dict[str, dict[str, int]]) -> None:
            lines.extend([f"## {title}", "", "| variant | n | success |", "|---|---|---|"])
            for k, v in d.items():
                lines.append(f"| {k} | {v['n']} | {_pct(v['success'], v['n'])} |")
            lines.append("")

        table("By env var × typo kind", s["by_target_kind"])
        table("By innocent change sharing the deploy commit", s["by_innocent_change"])
        for k, d in s.get("by_param", {}).items():
            if len(d) > 1:
                table(f"By {k}", d)
        table("By stop reason", s["by_stop_reason"])
        if s["failed_seeds"]:
            lines += ["## Failed seeds (triage)", "", "| seed | outcome | reward | steps | stop | hidden root cause |", "|---|---|---|---|---|---|"]
            for f in s["failed_seeds"]:
                lines.append(f"| {f['seed']} | {f['outcome']} | {f['reward']} | {f['steps']} | {f['stop_reason']} | {str(f['hidden_root_cause'])[:140]} |")
            lines.append("")
    else:
        lines.append("_no model results yet_")
    if s["infra_seeds"]:
        lines += ["## Infra errors (excluded, re-run to retry)", ""] + [f"- seed {i['seed']}: {i['error']}" for i in s["infra_seeds"]] + [""]
    return "\n".join(lines)
